print("Please enter the following information so I can sellit for a profit")
first_name=input("First name:")
last_name=input("Last name:")
Grade=int(input("Grade(9-12):"))
Student_id=int(input("Studend ID:"))
login=str(input("login:"))
GPA=float(input("GPA(0.0-4.0):"))
print(f"Your Information:\n\tlogin:{login}\n\tID:{Student_id}\n\tName:{last_name},{first_name}\n\tGPA:{GPA}\n\tGrade:{Grade}")
